# Generated by Django 5.2.5 on 2025-08-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                ("num", models.IntegerField(primary_key=True, serialize=False)),
                ("author", models.CharField(blank=True, max_length=10, null=True)),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("content", models.CharField(blank=True, max_length=4000, null=True)),
                ("bwrite", models.DateField(blank=True, null=True)),
                ("readcnt", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "board",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Buser",
            fields=[
                ("buserno", models.IntegerField(primary_key=True, serialize=False)),
                ("busername", models.CharField(max_length=10)),
                ("buserloc", models.CharField(blank=True, max_length=10, null=True)),
                ("busertel", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                "db_table": "buser",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Gogek",
            fields=[
                ("gogekno", models.IntegerField(primary_key=True, serialize=False)),
                ("gogekname", models.CharField(max_length=10)),
                ("gogektel", models.CharField(blank=True, max_length=20, null=True)),
                ("gogekjumin", models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                "db_table": "gogek",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Jikwon",
            fields=[
                ("jikwonno", models.IntegerField(primary_key=True, serialize=False)),
                ("jikwonname", models.CharField(max_length=10)),
                ("busernum", models.IntegerField()),
                ("jikwonjik", models.CharField(blank=True, max_length=10, null=True)),
                ("jikwonpay", models.IntegerField(blank=True, null=True)),
                ("jikwonibsail", models.DateField(blank=True, null=True)),
                ("jikwongen", models.CharField(blank=True, max_length=4, null=True)),
                ("jikwonrating", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                "db_table": "jikwon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                ("note_id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField(blank=True, null=True)),
                ("last_modified", models.DateTimeField()),
            ],
            options={
                "db_table": "notes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sangdata",
            fields=[
                ("code", models.IntegerField(primary_key=True, serialize=False)),
                ("sang", models.CharField(blank=True, max_length=20, null=True)),
                ("su", models.IntegerField(blank=True, null=True)),
                ("dan", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "sangdata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("pid", models.UUIDField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("nickname", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Survey",
        ),
    ]
