window.kakao=window.kakao||{},window.kakao.maps=window.kakao.maps||{},window.daum&&window.daum.maps?window.kakao.maps=window.daum.maps:(window.daum=window.daum||{},window.daum.maps=window.kakao.maps),function(){function t(){if(o.length){a(p[o.shift()],t).start()}else n()}function a(t,a){var n=document.createElement("script");return n.onload=a,n.onreadystatechange=function(){/loaded|complete/.test(this.readyState)&&a()},{start:function(){n.src=t||"",
document.getElementsByTagName("head")[0].appendChild(n),n=null}}}function n(){for(;u[0];)u.shift()();e.readyState=2}var e=kakao.maps=kakao.maps||{};if(void 0===e.readyState)e.onloadcallbacks=[],e.readyState=0;else if(2===e.readyState)return;e.URI_FUNC={ROADMAP:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNGSD02/v11_hdwvr/latest/"+n+"/"+a+"/"+t+".png"},HYBRID:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNGSD_SKYH02/v11_e6wip/latest/"+n+"/"+a+"/"+t+".png"},ROADVIEW:function(t,a,n){
return"mts.daumcdn.net/api/v1/tile/PNGSD_RV02/v08_d4bmj/latest/"+n+"/"+a+"/"+t+".png"},BICYCLE:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNGSD_BIKE02/v05_ytkuj/latest/"+n+"/"+a+"/"+t+".png"},USE_DISTRICT:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNGSD_CAD02/v08_kpcmc/latest/"+n+"/"+a+"/"+t+".png"},SR:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNGSD_SR02/v11_qcfpe/latest/"+n+"/"+a+"/"+t+".png"},BBOUND:function(t,a,n){
return"mts.daumcdn.net/api/v1/tile/PNGSD_BBOUND02/v08_qawd4/latest/"+n+"/"+a+"/"+t+".png"},HBOUND:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNGSD_HBOUND02/v08_oxema/latest/"+n+"/"+a+"/"+t+".png"},TRAFFIC:function(t,a,n){return"r.maps.daum-img.net/mapserver/file/realtimeroad/L"+n+"/"+a+"/"+t+".png"},ROADMAP_HD:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNG02/v11_kjfhk/latest/"+n+"/"+a+"/"+t+".png"},HYBRID_HD:function(t,a,n){
return"mts.daumcdn.net/api/v1/tile/PNG_SKYH02/v11_vhvkl/latest/"+n+"/"+a+"/"+t+".png"},ROADVIEW_HD:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNG_RV02/v08_76baa/latest/"+n+"/"+a+"/"+t+".png"},BICYCLE_HD:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNG_BIKE02/v05_y3qux/latest/"+n+"/"+a+"/"+t+".png"},USE_DISTRICT_HD:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNG_CAD02/v08_8tkdq/latest/"+n+"/"+a+"/"+t+".png"},SR_HD:function(t,a,n){
return"mts.daumcdn.net/api/v1/tile/PNGSD_SR02/v11_qcfpe/latest/"+n+"/"+a+"/"+t+".png"},BBOUND_HD:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNG_BBOUND02/v08_mvzlm/latest/"+n+"/"+a+"/"+t+".png"},HBOUND_HD:function(t,a,n){return"mts.daumcdn.net/api/v1/tile/PNG_HBOUND02/v08_juwvi/latest/"+n+"/"+a+"/"+t+".png"},TRAFFIC_HD:function(t,a,n){return"r.maps.daum-img.net/mapserver/file/realtimeroad_hd/L"+n+"/"+a+"/"+t+".png"}},e.VERSION={ROADMAP_SUFFIX:"",SKYVIEW_VERSION:"160114",
SKYVIEW_HD_VERSION:"160107"},e.RESOURCE_PATH={ROADVIEW_AJAX:"//t1.daumcdn.net/roadviewjscore/core/css3d/200204/standard/1580795088957/roadview.js",ROADVIEW_CSS:"//t1.daumcdn.net/roadviewjscore/core/openapi/standard/250728/roadview.js"}
;for(var i,s="https:"==location.protocol?"https:":"http:",r="",d=document.getElementsByTagName("script"),c=d.length;i=d[--c];)if(/\/(beta-)?dapi\.kakao\.com\/v2\/maps\/sdk\.js\b/.test(i.src)||/\/map_js_init\/open4\.test\.js\b/.test(i.src)||/\/map_js_init\/open4\.cbt\.js\b/.test(i.src)){r=i.src;break}d=null;var u=e.onloadcallbacks,o=["v3"],m="",p={v3:s+"//t1.daumcdn.net/mapjsapi/js/main/4.4.19/kakao.js",services:s+"//t1.daumcdn.net/mapjsapi/js/libs/services/1.0.2/services.js",
drawing:s+"//t1.daumcdn.net/mapjsapi/js/libs/drawing/1.2.6/drawing.js",clusterer:s+"//t1.daumcdn.net/mapjsapi/js/libs/clusterer/1.0.9/clusterer.js"},l=function(t){var a={};return t.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(t,n,e){a[n]=e}),a}(r);m=l.appkey,m&&(e.apikey=m),e.version="4.4.19";var v=l.libraries;if(v&&(o=o.concat(v.split(","))),"false"!==l.autoload){for(var c=0,_=o.length;c<_;c++)!function(t){t&&document.write('<script charset="UTF-8" src="'+t+'"><\/script>')}(p[o[c]])
;e.readyState=2}e.load=function(a){switch(u.push(a),e.readyState){case 0:e.readyState=1,t();break;case 2:n()}}}();